# Based on https://github.com/khulnasoft/ml-buildkit/blob/v0.6.18/workflows/build-pipeline.yml
name: build-pipeline

on:
  workflow_dispatch:
    inputs:
      build_args:
        description: "Arguments passed to build script"
        required: false
      working_directory:
        description: "Working directory from where the build command is run"
        required: false
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set-host-ip
        run: echo "_HOST_IP=$(hostname -I | cut -d ' ' -f 1)" >> "$GITHUB_ENV"

      - name: run-build-scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: ${{ github.event.inputs.build_args || secrets.BUILD_ARGS }}
          working_directory: ${{ github.event.inputs.working_directory || secrets.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}